export { createRecordingArtifactStore, RECORDING_DOCUMENT_PATH, STEPS_DOCUMENT_PATH } from './artifact/createRecordingArtifactStore.ts'
export type { CapturedPreview, CapturedRawEvent, CapturedRecording, RecordingArtifactReader, RecordingArtifactStore } from './artifact/createRecordingArtifactStore.ts'
export { getRecordingScreenshotFileName, getRecordingSnapshotFileName, parseRecordingSnapshot, serializeRecordingSnapshot } from './artifact/recordingSnapshot.ts'
export { formatPlaywrightLocator } from './formats/playwright/formatPlaywrightLocator.ts'
export type { FormatPlaywrightLocatorOptions } from './formats/playwright/formatPlaywrightLocator.ts'
export { generatePlaywrightScript } from './formats/playwright/generatePlaywrightScript.ts'
export { generateThousandEyesScript } from './formats/thousandeyes/generateThousandEyesScript.ts'
export type { ThousandEyesTransactionScript } from './formats/thousandeyes/types.ts'
export { createRecording, parseRecording, serializeRecording } from './recording/recording.ts'
export { recordingSchema } from './recording/recordingSchema.ts'
export type { RawEvent, Recording, RecordingMetadata } from './recording/recordingSchema.ts'
export type { RecordedAriaNode, RecordedAriaSnapshot, RecordedLocator, RecordedValue } from './shared/recordedDataSchema.ts'
export type { ActionStep } from './steps/actionStepSchema.ts'
export { deriveRecordingSteps } from './steps/deriveRecordingSteps.ts'
export { insertAnnotationStep, readStepAnnotations, removeMarkerSteps, renameMarkerSteps, validateStepAnnotationUpdate } from './steps/recordingStepAnnotations.ts'
export type { StepAnnotations, StepMarker, StepScreenshot } from './steps/recordingStepAnnotations.ts'
export { getActionSteps, isActionStep, parseRecordingSteps, serializeRecordingSteps } from './steps/recordingSteps.ts'
export { recordingStepsSchema } from './steps/recordingStepsSchema.ts'
export type { AnnotationStep, MarkerEndStep, MarkerStartStep, RecordingStep, RecordingSteps, ScreenshotStep } from './steps/recordingStepsSchema.ts'
