export { createRecording } from './recording/createRecording.ts'
export { formatPlaywrightLocator } from './codecs/playwright/formatPlaywrightLocator.ts'
export type { FormatPlaywrightLocatorOptions } from './codecs/playwright/formatPlaywrightLocator.ts'
export { generatePlaywrightScript } from './codecs/playwright/generatePlaywrightScript.ts'
export { parseRecording } from './recording/parseRecording.ts'
export { recordingSchema } from './recording/recordingSchema.ts'
export { serializeRecording } from './recording/serializeRecording.ts'
export { getRecordingSnapshotFileName, parseRecordingSnapshot, serializeRecordingSnapshot } from './recording/recordingSnapshot.ts'
export type { RecordedAction, RecordedAriaNode, RecordedAriaSnapshot, RecordedLocator, RecordedValue, Recording } from './recording/recordingSchema.ts'
export { createRecordingSession } from './recording/createRecordingSession.ts'
export type { RecordingSession } from './recording/createRecordingSession.ts'
export type { PlaybackObserver, PlaybackResult } from './playback/types.ts'
export type { ThousandEyesTransactionCodec, ThousandEyesTransactionScript } from './codecs/thousandeyes/types.ts'
