import { build } from 'esbuild'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { svelteEsbuildPlugin } from '@te/recorder-utils/build/svelte-esbuild-plugin'

const SCRIPT_DIRECTORY = dirname(fileURLToPath(import.meta.url))
const CAPTURE_DIRECTORY = join(SCRIPT_DIRECTORY, '..')
const ROOT_DIRECTORY = join(CAPTURE_DIRECTORY, '..', '..')
const GENERATED_DIRECTORY = join(CAPTURE_DIRECTORY, 'generated')

await generate()

async function generate() {
  const [ariaPackage, capturePackage] = await Promise.all([readJson(join(ROOT_DIRECTORY, 'packages', 'aria', 'package.json')), readJson(join(CAPTURE_DIRECTORY, 'package.json'))])
  const playwrightVersion = ariaPackage.devDependencies?.playwright
  const capturePlaywrightVersion = capturePackage.peerDependencies?.playwright

  if (!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(playwrightVersion ?? '')) {
    throw new Error('Expected an exact playwright version in the ARIA package metadata')
  }
  if (capturePlaywrightVersion !== playwrightVersion) {
    throw new Error(`Playwright version mismatch: ARIA uses ${playwrightVersion}, but capture requires ${capturePlaywrightVersion ?? 'nothing'}`)
  }

  await writeGeneratedSource(
    'recordingRuntimeSource',
    await bundle(join(CAPTURE_DIRECTORY, 'injected', 'entry.ts'), {
      banner: `/*! Playwright v${playwrightVersion} | Apache-2.0 | Copyright Microsoft Corporation */`,
      globalName: 'ariaRuntime',
    }),
  )
  process.stdout.write(`Generated injected recorder runtime from Playwright ${playwrightVersion}\n`)
}

async function bundle(entryPoint, options = {}) {
  return (
    await build({
      ...(options.banner ? { banner: { js: options.banner } } : {}),
      bundle: true,
      entryPoints: [entryPoint],
      format: 'iife',
      ...(options.globalName ? { globalName: options.globalName } : {}),
      legalComments: 'none',
      minify: true,
      platform: 'browser',
      plugins: [svelteEsbuildPlugin],
      write: false,
    })
  ).outputFiles[0].text
}

async function writeGeneratedSource(exportName, source) {
  await mkdir(GENERATED_DIRECTORY, { recursive: true })
  await writeFile(join(GENERATED_DIRECTORY, `${exportName}.generated.ts`), `export { ${exportName} }\n\n// Generated by packages/capture/scripts/generateInjectedRuntime.mjs. Do not edit.\nconst ${exportName} =\n  ${quoteJavaScriptString(source)}\n`)
}

function quoteJavaScriptString(value) {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'").replaceAll('\r', '\\r').replaceAll('\n', '\\n').replaceAll('\u2028', '\\u2028').replaceAll('\u2029', '\\u2029')}'`
}

async function readJson(path) {
  return JSON.parse(await readFile(path, 'utf8'))
}
