import { build } from 'esbuild'
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const SCRIPT_DIRECTORY = dirname(fileURLToPath(import.meta.url))
const RUNTIME_DIRECTORY = join(SCRIPT_DIRECTORY, '..')
const ROOT_DIRECTORY = join(RUNTIME_DIRECTORY, '..')
const RUNTIME_SOURCE = join(RUNTIME_DIRECTORY, 'recording', 'injected', 'ariaRuntimeSource.ts')

await generate()

async function generate() {
  const [ariaPackage, runtimePackage] = await Promise.all([readJson(join(ROOT_DIRECTORY, 'aria', 'package.json')), readJson(join(RUNTIME_DIRECTORY, 'package.json'))])
  const playwrightVersion = ariaPackage.devDependencies?.playwright
  const runtimePlaywrightVersion = runtimePackage.peerDependencies?.playwright
  const exactVersion = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/

  if (!exactVersion.test(playwrightVersion ?? '')) {
    throw new Error('Expected an exact playwright version in the ARIA package metadata')
  }
  if (runtimePlaywrightVersion !== playwrightVersion) {
    throw new Error(`Playwright version mismatch: ARIA uses ${playwrightVersion}, but runtime requires ${runtimePlaywrightVersion ?? 'nothing'}`)
  }

  const bundled = (
    await build({
      banner: { js: `/*! Playwright v${playwrightVersion} | Apache-2.0 | Copyright Microsoft Corporation */` },
      bundle: true,
      entryPoints: [join(ROOT_DIRECTORY, 'aria', 'browser.ts')],
      format: 'iife',
      globalName: 'ariaRuntime',
      legalComments: 'none',
      minify: true,
      platform: 'browser',
      write: false,
    })
  ).outputFiles[0].text
  const moduleSource = `export { ariaRuntimeSource }\n\n// Generated by runtime/scripts/generateAriaRuntime.mjs. Do not edit.\nconst ariaRuntimeSource =\n  ${quoteJavaScriptString(bundled)}\n`

  await writeFile(RUNTIME_SOURCE, moduleSource)
  process.stdout.write(`Generated ARIA runtime from Playwright ${playwrightVersion}\n`)
}

function quoteJavaScriptString(value) {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'").replaceAll('\r', '\\r').replaceAll('\n', '\\n').replaceAll('\u2028', '\\u2028').replaceAll('\u2029', '\\u2029')}'`
}

async function readJson(path) {
  return JSON.parse(await readFile(path, 'utf8'))
}
