import { build } from 'esbuild'
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const SCRIPT_DIRECTORY = dirname(fileURLToPath(import.meta.url))
const RUNTIME_DIRECTORY = join(SCRIPT_DIRECTORY, '..')
const ROOT_DIRECTORY = join(RUNTIME_DIRECTORY, '..')
const GENERATED_DIRECTORY = join(RUNTIME_DIRECTORY, 'injected', 'generated')

await generate()

async function generate() {
  const [ariaPackage, runtimePackage] = await Promise.all([readJson(join(ROOT_DIRECTORY, 'aria', 'package.json')), readJson(join(RUNTIME_DIRECTORY, 'package.json'))])
  const playwrightVersion = ariaPackage.devDependencies?.playwright
  const runtimePlaywrightVersion = runtimePackage.peerDependencies?.playwright
  const exactVersion = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/

  if (!exactVersion.test(playwrightVersion ?? '')) {
    throw new Error('Expected an exact playwright version in the ARIA package metadata')
  }
  if (runtimePlaywrightVersion !== playwrightVersion) {
    throw new Error(`Playwright version mismatch: ARIA uses ${playwrightVersion}, but runtime requires ${runtimePlaywrightVersion ?? 'nothing'}`)
  }

  const [ariaRuntimeSource, recordingCaptureSource, recordingOverlaySource] = await Promise.all([
    bundle(join(ROOT_DIRECTORY, 'aria', 'src', 'browser.ts'), { banner: `/*! Playwright v${playwrightVersion} | Apache-2.0 | Copyright Microsoft Corporation */`, globalName: 'ariaRuntime' }),
    bundle(join(RUNTIME_DIRECTORY, 'injected', 'capture', 'entry.ts')),
    bundle(join(RUNTIME_DIRECTORY, 'injected', 'overlay', 'entry.ts')),
  ])

  await Promise.all([writeGeneratedSource('ariaRuntimeSource', ariaRuntimeSource), writeGeneratedSource('recordingCaptureSource', recordingCaptureSource), writeGeneratedSource('recordingOverlaySource', recordingOverlaySource)])
  process.stdout.write(`Generated injected recorder runtime from Playwright ${playwrightVersion}\n`)
}

async function bundle(entryPoint, options = {}) {
  return (
    await build({
      ...(options.banner ? { banner: { js: options.banner } } : {}),
      bundle: true,
      entryPoints: [entryPoint],
      format: 'iife',
      ...(options.globalName ? { globalName: options.globalName } : {}),
      legalComments: 'none',
      minify: true,
      platform: 'browser',
      write: false,
    })
  ).outputFiles[0].text
}

async function writeGeneratedSource(exportName, source) {
  const moduleSource = `export { ${exportName} }\n\n// Generated by runtime/scripts/generateInjectedRuntime.mjs. Do not edit.\nconst ${exportName} =\n  ${quoteJavaScriptString(source)}\n`

  await writeFile(join(GENERATED_DIRECTORY, `${exportName}.generated.ts`), moduleSource)
}

function quoteJavaScriptString(value) {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'").replaceAll('\r', '\\r').replaceAll('\n', '\\n').replaceAll('\u2028', '\\u2028').replaceAll('\u2029', '\\u2029')}'`
}

async function readJson(path) {
  return JSON.parse(await readFile(path, 'utf8'))
}
