const { buildSync } = require('esbuild')
const { writeFileSync } = require('node:fs')
const { join } = require('node:path')

const bundled = buildSync({
  banner: { js: '/*! Playwright v1.59.1 | Apache-2.0 | Copyright Microsoft Corporation; dom-accessibility-api v0.7.1 | MIT | Copyright 2020 Sebastian Silbermann */' },
  bundle: true,
  entryPoints: [require.resolve('@te/aria/browser')],
  format: 'iife',
  globalName: 'ariaRuntime',
  legalComments: 'none',
  minify: true,
  platform: 'browser',
  write: false,
}).outputFiles[0].text
const quotedSource = `'${bundled.replaceAll('\\', '\\\\').replaceAll("'", "\\'").replaceAll('\r', '\\r').replaceAll('\n', '\\n').replaceAll('\u2028', '\\u2028').replaceAll('\u2029', '\\u2029')}'`
const moduleSource = `export { ariaRuntimeSource }\n\n// Generated by generateAriaRuntimeSource.cjs.\nconst ariaRuntimeSource =\n  ${quotedSource}\n`

writeFileSync(join(__dirname, 'ariaRuntimeSource.ts'), moduleSource)
